FROM ubuntu:18.04
MAINTAINER ACSONE SA/NV

COPY ./install /tmp/install
RUN set -x \
  && /tmp/install/pre-install.sh \
  && /tmp/install/tools.sh \
  && /tmp/install/confd.sh \
  && /tmp/install/gosu.sh \
  && /tmp/install/python2.sh \
  && /tmp/install/wkhtml_12_4.sh \
  && /tmp/install/odoo-deps-8.0.sh \
  && /tmp/install/post-install-clean.sh \
  && rm -r /tmp/install

ENV \
  ODOO_VERSION=8.0 \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  OPENERP_SERVER=/etc/odoo.cfg \
  PATH=/odoo/bin:$PATH

COPY ./8.0/confd /etc/confd

RUN mkdir -p /data/odoo
VOLUME ["/data/odoo"]

EXPOSE 8069 8072

COPY ./bin/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["openerp-server"]
