FROM ubuntu:18.04
MAINTAINER ACSONE SA/NV

ARG PYTHONBIN=python2.7

ENV \
  ODOO_VERSION=10.0 \
  ODOO_BIN=odoo \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  DEBIAN_FRONTEND=noninteractive \
  KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf


COPY ./install /tmp/install
RUN set -x \
  && /tmp/install/pre-install.sh \
  && /tmp/install/tools.sh \
  && /tmp/install/confd.sh \
  && /tmp/install/gosu.sh \
  && /tmp/install/python2.sh \
  && /tmp/install/lessc.sh \
  && /tmp/install/wkhtmltopdf.sh \
  && /tmp/install/pgdg.sh \
  && /tmp/install/post-install-clean.sh \
  && rm -r /tmp/install

# isolate from system python libraries
RUN $PYTHONBIN -m virtualenv /odoo
ENV PATH=/odoo/bin:$PATH

# odoo config file
COPY ./confd/${ODOO_VERSION} /etc/confd
ENV OPENERP_SERVER=/etc/odoo.cfg

# odoo data dir (filestore, etc)
RUN mkdir -p /data/odoo
VOLUME ["/data/odoo"]

EXPOSE 8069 8072

# root banner
COPY ./root-banner /etc
RUN echo "cat /etc/root-banner" >> /root/.bashrc

RUN mkdir -p /odoo/start-entrypoint.d
COPY ./bin/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["odoo"]
