FROM ubuntu:18.04
MAINTAINER ACSONE SA/NV

ENV \
  ODOO_VERSION=8.0 \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  DEBIAN_FRONTEND=noninteractive

COPY ./install /tmp/install
RUN set -x \
  && /tmp/install/pre-install.sh \
  && /tmp/install/tools.sh \
  && /tmp/install/confd.sh \
  && /tmp/install/gosu.sh \
  && /tmp/install/python2.sh \
  && /tmp/install/wkhtml_12_4.sh \
  && /tmp/install/odoo-deps-${ODOO_VERSION}.sh \
  && /tmp/install/post-install-clean.sh \
  && rm -r /tmp/install

# isolate from system python libraries
RUN python -m virtualenv /odoo
ENV PATH=/odoo/bin:$PATH

# odoo config file
COPY ./confd/${ODOO_VERSION} /etc/confd
ENV OPENERP_SERVER=/etc/odoo.cfg

# odoo data dir (filestore, etc)
RUN mkdir -p /data/odoo
VOLUME ["/data/odoo"]

EXPOSE 8069 8072

COPY ./bin/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["openerp-server"]
