#!/bin/bash

# Copyright 2016-2022 Camptocamp SA (http://www.camptocamp.com)
# Copyright 2023 ACSONE SA (http://acsone.eu)

DOMAIN="${ODOO_REPORT_URL}"

if [ -n "$DOMAIN" ]; then

  if ! command -v psql &> /dev/null
  then
      echo "Command 'psql' could not be found, skipping $0"
      exit
  fi

  if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
  then
      echo "Database $DB_NAME does not exist, skipping $0"
      exit 0
  fi

  if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
  then
      echo "Database $DB_NAME not initialized, skipping $0"
      exit 0
  fi

  echo "Setting Report URL to ${DOMAIN}"
  psql --quiet << EOF

  WITH update_param AS (
    UPDATE ir_config_parameter
    SET value = '${DOMAIN}'
    WHERE key = 'report.url'
    RETURNING *
  )
  INSERT INTO ir_config_parameter
  (value, key, create_uid, write_uid, create_date, write_date)
  SELECT '${DOMAIN}', 'report.url', 1, 1, now(), now()
  WHERE NOT EXISTS (SELECT * FROM update_param);

EOF
fi
