name: Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 4 * * 0"

jobs:
  build-odoo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ODOOVERSION: "11.0"
            PYTHONTAG: py36
            PYTHONBIN: python3.6
          - ODOOVERSION: "12.0"
            PYTHONTAG: py36
            PYTHONBIN: python3.6
          - ODOOVERSION: "12.0"
            PYTHONTAG: py37
            PYTHONBIN: python3.7
          - ODOOVERSION: "13.0"
            PYTHONTAG: py36
            PYTHONBIN: python3.6
          - ODOOVERSION: "13.0"
            PYTHONTAG: py37
            PYTHONBIN: python3.7
          - ODOOVERSION: "13.0"
            PYTHONTAG: py310
            PYTHONBIN: python3.10
          - ODOOVERSION: "14.0"
            PYTHONTAG: py36
            PYTHONBIN: python3.6
          - ODOOVERSION: "14.0"
            PYTHONTAG: py37
            PYTHONBIN: python3.7
          - ODOOVERSION: "14.0"
            PYTHONTAG: py38
            PYTHONBIN: python3.8
          - ODOOVERSION: "14.0"
            PYTHONTAG: py39
            PYTHONBIN: python3.9
          - ODOOVERSION: "15.0"
            PYTHONTAG: py38
            PYTHONBIN: python3.8
          - ODOOVERSION: "15.0"
            PYTHONTAG: py39
            PYTHONBIN: python3.9
          - ODOOVERSION: "16.0"
            PYTHONTAG: py39
            PYTHONBIN: python3.9
          - ODOOVERSION: "16.0"
            PYTHONTAG: py310
            PYTHONBIN: python3.10
          - ODOOVERSION: "16.0"
            PYTHONTAG: py311
            PYTHONBIN: python3.11
          - ODOOVERSION: "17.0"
            PYTHONTAG: py311
            PYTHONBIN: python3.11
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-${{ matrix.ODOOVERSION }}
          build-args: |
            PYTHONBIN=${{ matrix.PYTHONBIN }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.ODOOVERSION }}-${{ matrix.PYTHONTAG }}-latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ matrix.ODOOVERSION }}-${{ matrix.PYTHONTAG }}-latest
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true
      - name: Install test pre-requisites
        run: pip install pytest
      - name: Test
        env:
          ODOOVERSION: "${{ matrix.ODOOVERSION }}"
          PYTHONTAG: "${{ matrix.PYTHONTAG }}"
        run: pytest -v tests
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-${{ matrix.ODOOVERSION }}
          build-args: |
            PYTHONBIN=${{ matrix.PYTHONBIN }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.ODOOVERSION }}-${{ matrix.PYTHONTAG }}-latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=inline
          push: true
        if: ${{ github.repository_owner == 'acsone' && github.ref == 'refs/heads/master' }}
